l_english:

 ### Toggle subject colour stuffs
 vu_toggle_subject_colours_overlord_title:0 "§YToggle Your Subjects colouring in.§!"
 vu_toggle_subject_colours_overlord_desc:0 "This will toggle between your subject being coloured in or not. (also colours in your subject's subjects too)"
 vu_toggle_subject_colours_subject_title:0 "§YToggle Yourself and other subjects colouring in.§!"
 vu_toggle_subject_colours_subject_desc:0 "This will toggle between you and other subjects of your overlord being coloured in or not."
 ## Random Theodoro decision
 vu_FEO_GTFO_title:0 "§b Let's get the fuck away from that. §!"
 vu_FEO_GTFO_desc:0 "§R RUN. §!"
 ### Settings Event Chain
 
 VU_SET_Events.01.t: "Victorum Universalis Settings"
 VU_SET_Events.01.d: "Welcome to Victorum Universalis!\nThis event is here to help you set up the most enjoyable experience for the mod.\n\nThe §G'Recommended Mode'§! is how I personally recommend you play if it's your first time with the mod, so you can fully experience all the new provinces, nations, cultures, religions and content the mod adds.\nBut due to all our extra content, the game might run slowly for some, so you could try §T'Performance Mode'§! and see if it helps.\n\nThere is also an event chain where you can manually select each of the options to create the experience you would enjoy!\nEach of the events will also explain how each setting works in case you are interested.\n\nWe hope you enjoy playing this mod as much as we enjoyed making it!\n- The Victorum Universalis Dev Team"
 VU_SET_Events.01.a: "Enable §GRecommended§! Mode" #All the (Recommended) options.
 VU_SET_Events.01.b: "Enable §TPerformance§! Mode" #All the (Performance) options when available, (Recommended) when not.
 VU_SET_Events.01.c: "I wish to pick each option myself"
 
 VU_SET_Events.01.b.tt: "§GThe game may freeze for a minute, but just wait and it will resume.§!"

 VU_SET_Events.02.t: "Specific Settings"
 VU_SET_Events.02.d: "Here you can select from categories, and choose whichever settings suit you.\n\nClosing the settings will apply all selected settings to the game. §RThis is IREVERSIBLE§!"
 VU_SET_Events.02.a: "§TPerformance Settings§!" #Nothing happens
 VU_SET_Events.02.b: "§GGameplay Settings§!" #VU_SET_Events.03 - Gameplay settings
 VU_SET_Events.02.e: "§RFun Settings§!" #VU_SET_Events.05 - Fun gameplay settings
 VU_SET_Events.02.c: "§YClose Settings§!" #Close and Apply settings

 VU_SET_Events.03.t: "Gameplay Settings"
 VU_SET_Events.03.d: "Here you may select what gameplay options you wish to enable/disable."
 VU_SET_Events.03.ay: "§YSubjects colouring in §!§GON§!"
 VU_SET_Events.03.an: "§YSubjects colouring in §!§ROFF§!"
 vu_startup_disable_hard_to_colonise: "§YHard to colonise§! will be disabled"
 VU_SET_Events.03.by: "§YHard to Colonise §!§GON§!"
 VU_SET_Events.03.bn: "§YHard to Colonise §!§ROFF§!"
 vu_startup_disable_subject_colouring: "§YSubject colouring§! will be disabled"
 VU_SET_Events.03.cy: "§YHistorical Colonisation §!§GON§!"
 VU_SET_Events.03.cn: "§YHistorical Colonisation §!§ROFF§!"
 vu_no_historical_colonization: "§YHistorical colonisation§! will be disabled"
 VU_SET_Events.03.q: "Return back"

 VU_SET_Events.04.t: "Performance Settings"
 VU_SET_Events.04.d: "Here you may select what areas you wish to simplify (remove all minor tags that don't affect the gameplay too much)."
 VU_SET_Events.04.ay: "§YExpanded HRE §!§GON§!"
 VU_SET_Events.04.an: "§YExpanded HRE §!§ROFF§!"
 vu_startup_simplify_HRE: "§YHRE§! will be simplified."
 VU_SET_Events.04.by: "§YExpanded Western Europe §!§GON§!"
 VU_SET_Events.04.bn: "§YExpanded Western Europe §!§ROFF§!"
 vu_startup_simplify_western_europe: "§YWestern Europe§! will be simplified."
 VU_SET_Events.04.cy: "§YExpanded Italy §!§GON§!"
 VU_SET_Events.04.cn: "§YExpanded Italy §!§ROFF§!"
 vu_startup_simplify_italy: "§YItaly§! will be simplified."
 VU_SET_Events.04.dy:0 "§YExpanded Switzerland §!§GON§!"
 VU_SET_Events.04.dn:0 "§YExpanded Switzerland §!§ROFF§!"
 vu_startup_simplify_switzerland: "§YSwitzerland§! will be simplified."
 VU_SET_Events.04.ey:0 "§YExpanded Middle East §!§GON§!"
 VU_SET_Events.04.en:0 "§YExpanded Middle East §!§ROFF§!"
 vu_startup_simplify_middle_east: "§YMiddle East§! will be simplified."
 VU_SET_Events.04.fy:0 "§YExpanded Balkans §!§GON§!"
 VU_SET_Events.04.fn:0 "§YExpanded Balkans §!§ROFF§!"
 vu_startup_simplify_balkans: "§YBalkans§! will be simplified."
 VU_SET_Events.04.gy:0 "§YExpanded Eastern Europe §!§GON§!"
 VU_SET_Events.04.gn:0 "§YExpanded Eastern Europe §!§ROFF§!"
 vu_startup_simplify_eastern_europe: "§YEastern Europe§! will be simplified."
 VU_SET_Events.04.hy:0 "§YExpanded India §!§GON§!"
 VU_SET_Events.04.hn:0 "§YExpanded India §!§ROFF§!"
 vu_startup_simplify_india: "§YIndia§! will be simplified."
 VU_SET_Events.04.iy:0 "§YExpanded Africa §!§GON§!"
 VU_SET_Events.04.in:0 "§YExpanded Africa §!§ROFF§!"
 vu_startup_simplify_afrika: "§YAfrica§! will be simplified."
 VU_SET_Events.04.q: "Return back"

 VU_SET_Events.05.t: "Fun Settings"
 VU_SET_Events.05.d: "These are more of a fun way to change up your game, add some flavour or just cause some general chaos if you wish so."
 VU_SET_Events.05.ay: "Shattered World §ROFF§! §Y(Will cause Immense lag!)§!"
 VU_SET_Events.05.an: "Shattered World §GON§! §Y(Will cause Immense lag!)§!"
 vu_startup_shattered_world: "§YWorld§! shall be shattered!"
 VU_SET_Events.05.by: "Release Subjects §ROFF§!"
 VU_SET_Events.05.bn: "Release Subjects §GON§!"
 vu_startup_release_all_subjects: "§YSubjects§! shall be splintered!"

 VU_SET_Events.06.t: "§RYou're Missing DLCs!§!"
 VU_SET_Events.06.d: "There are some DLCs you're §RMissing§!, VU is not made to run without all of the DLCs §GEnabled§!, so for the full VU experience please §GEnable§! them, below you can see a list of all the DLCs you're §RMissing§!. \n\nPlease also do keep in mind that VU §RCannot§! detect if you're §RMissing§! §JCosmetic packs§!, §JCosmetic packs§! include unit sprites, and not having them is known to §RCrash§! the game. If you're seeing this event then it's likely that you're §RMissing§! §JCosmetic packs§! too, so please check manually that you have them all."
 VU_SET_Events.06.l1: "For a complete list of all §JExpansions§!/§JImmersion packs§! you can refer yourself to:"
 VU_SET_Events.06.l2: "https://eu4.paradoxwikis.com/Downloadable_content#Expansions\n"
 VU_SET_Events.06.l3: "For a complete list of all §JCosmetic packs§! you can refer yourself to:"
 VU_SET_Events.06.l4: "https://eu4.paradoxwikis.com/Downloadable_content_2#Cosmetic_packs"
 VU_SET_Events.06.1: "Missing: §RConquest of Paradise§!"
 VU_SET_Events.06.2: "Missing: §RWealth of Nations§!"
 VU_SET_Events.06.3: "Missing: §RRes Publica§!"
 VU_SET_Events.06.4: "Missing: §REl Dorado§!"
 VU_SET_Events.06.5: "Missing: §RThe Cossacks§!"
 VU_SET_Events.06.6: "Missing: §RMare Nostrum§!"
 VU_SET_Events.06.7: "Missing: §RMandate of Heaven§!"
 VU_SET_Events.06.8: "Missing: §RCradle of Civilization§!"
 VU_SET_Events.06.9: "Missing: §RDharma§!"
 VU_SET_Events.06.10: "Missing: §REmperor§!"
 VU_SET_Events.06.11: "Missing: §RLeviathan§!"
 VU_SET_Events.06.12: "Missing: §RDomination§!"
 VU_SET_Events.06.13: "Missing: §RWinds of Change§!"
 VU_SET_Events.06.14: "Missing: §RThird Rome§!"
 VU_SET_Events.06.15: "Missing: §RRule Britannia§!"
 VU_SET_Events.06.16: "Missing: §RGolden Century§!"
 VU_SET_Events.06.17: "Missing: §ROrigins§!"
 VU_SET_Events.06.18: "Missing: §RLions of the North§!"
 VU_SET_Events.06.19: "Missing: §RKing of Kings§!"
 VU_SET_Events.06.20: "Error: §RNot Missing any DLCs§!"